name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global

      - name: Authenticate Dev Org
        run: |
          echo "${{ secrets.DEV_SFDX_AUTH_URL }}" > sfdx_auth.txt
          sfdx auth:sfdxurl:store -f sfdx_auth.txt -a DevSandbox

      - name: Deploy Metadata to Dev
        run: |
          sfdx force:source:deploy -p force-app/main/default,core/main/default,utility/main/default \
          -u DevSandbox --testlevel RunLocalTests
