name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          sudo apt-get update
          sudo apt-get install wget unzip -y
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
          ./sfdx/install
          sfdx version

      - name: Authenticate Dev Org
        run: |
          echo "${{ secrets.DEV_SFDX_AUTH_URL }}" > sfdx_auth.txt
          sfdx auth:sfdxurl:store -f sfdx_auth.txt -a DevSandbox

      - name: Deploy Metadata to Dev
        run: |
          sfdx force:source:deploy -p force-app/main/default,core/main/default,utility/main/default \
          -u DevSandbox --testlevel RunLocalTests
