name: Rollback Deployment

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          sudo apt-get update
          sudo apt-get install wget unzip -y
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
          ./sfdx/install
          sfdx version

      - name: Authenticate Production Org
        run: |
          echo "${{ secrets.PROD_SFDX_AUTH_URL }}" > sfdx_auth.txt
          sfdx auth:sfdxurl:store -f sfdx_auth.txt -a ProdOrg

      - name: Rollback to Last Successful Deployment
        run: |
          sfdx force:source:deploy -p backup/last-successful -u ProdOrg --testlevel RunLocalTests
