name: Run Apex Tests

on:
  pull_request:
    branches:
      - dev
      - uat
      - main

jobs:
  apex-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: |
          sudo apt-get update
          sudo apt-get install wget unzip -y
          wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
          mkdir sfdx
          tar xJf sfdx-linux-amd64.tar.xz -C sfdx --strip-components 1
          ./sfdx/install
          sfdx version

      - name: Authenticate Dev Org
        run: |
          echo "${{ secrets.DEV_SFDX_AUTH_URL }}" > sfdx_auth.txt
          sfdx auth:sfdxurl:store -f sfdx_auth.txt -a DevSandbox

      - name: Run Apex Tests
        run: |
          sfdx force:apex:test:run -u DevSandbox --resultformat human --codecoverage --wait 10
      - name: Send Email on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚨 Salesforce Apex Test Failure on branch ${{ github.ref }}"
          to: apadmajan650@gmail.com
          from: ci-cd@yourcompany.com
          body: |
            Apex tests failed on branch ${{ github.ref }}.
            Check logs here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
