name: Salesforce CI/CD - Multi-Package Deployment & Apex Tests

on:
  push:
    branches: [dev]

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Install Salesforce CLI
      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      # Step 3: Authenticate to DevSandbox
      - name: Authenticate to DevSandbox
        run: echo "${{ secrets.DEV_SFDX_AUTH_URL }}" | sf auth:sfdxurl:store --alias DevSandbox --sfdx-url-stdin

      # Step 4: Deploy multiple packages (adjust paths as needed)
      - name: Deploy All Packages
        run: |
          sf project deploy start --source-dir force-app/main/default,core/main/default,utility/main/default --target-org DevSandbox --test-level RunLocalTests

      # Step 5: Run Apex tests with code coverage
      - name: Run Apex Tests with Coverage
        run: sf apex run test --target-org DevSandbox --result-format human --code-coverage --wait 10

      # Step 6: Send email notification on failure
      - name: Send Email on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚨 Salesforce Apex Test Failure on branch ${{ github.ref }}"
          to: apadmajan650@gmail.com
          from: ci-cd@yourcompany.com
          body: |
            Apex tests failed on branch ${{ github.ref }}.
            Check logs here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
