name: Run Apex Tests

on:
  pull_request:
    branches:
      - dev
      - uat
      - main

jobs:
  apex-tests:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2️⃣ Install Salesforce CLI
      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global

      # 3️⃣ Authenticate DevSandbox
      - name: Authenticate to DevSandbox
        run: echo "${{ secrets.DEV_SF_AUTH_URL }}" | sf auth:sfdxurl:store --alias DevSandbox --sfdx-url-stdin

      # 4️⃣ Verify authentication (optional but recommended)
      - name: Verify DevSandbox Auth
        run: sfdx force:org:display -u DevSandbox

      # 5️⃣ Run Apex Tests
      - name: Run Apex Tests
        run: sfdx force:apex:test:run -u DevSandbox --resultformat human --codecoverage --wait 10

      # 6️⃣ Send email if tests fail
      - name: Send Email on Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚨 Salesforce Apex Test Failure on branch ${{ github.ref }}"
          to: apadmajan650@gmail.com
          from: ci-cd@yourcompany.com
          body: |
            Apex tests failed on branch ${{ github.ref }}.
            Check logs here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
