name: Validate Metadata

on:
  push:
    branches:
      - dev

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global

      - name: Authenticate to DevSandbox
        run: echo "${{ secrets.DEV_SF_AUTH_URL }}" | sf auth:sfdxurl:store --alias DevSandbox --sfdx-url-stdin

      - name: Validate Metadata Deployment
        run: |
          sfdx force:source:deploy -p force-app/main/default,core/main/default,utility/main/default \
          -u DevSandbox --checkonly --ignorewarnings --json
      