name: Validate Metadata

on:
  push:
    branches:
      - dev

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout Repo
        uses: actions/checkout@v3

      # 2️⃣ Install Salesforce CLI
      - name: Install Salesforce CLI
        run: npm install sfdx-cli --global

      # 3️⃣ Authenticate DevSandbox using sfdx
      - name: Authenticate to DevSandbox
        run: |
          # Clean secret and save to file
          echo "${{ secrets.DEV_SFDX_AUTH_URL }}" | tr -d '\r' > sfdx_auth.txt
          
          # Authenticate and set default username
          sfdx auth:sfdxurl:store -f sfdx_auth.txt --alias DevSandbox --setdefaultusername

      # 4️⃣ Verify authentication
      - name: Verify DevSandbox Auth
        run: sfdx force:org:display -u DevSandbox

      # 5️⃣ Validate Metadata Deployment
      - name: Validate Metadata Deployment
        run: |
          sfdx force:source:deploy \
          -p force-app/main/default,core/main/default,utility/main/default \
          -u DevSandbox \
          --checkonly \
          --ignorewarnings \
          --json

      # 6️⃣ Send Email on Failure
      - name: Send Email on Validation Failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚨 Validation Failure on branch ${{ github.ref }}"
          to: apadmajan650@gmail.com
          from: ci-cd@yourcompany.com
          body: |
            Validation failed on branch ${{ github.ref }}.
            Check logs here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
